package com.deppon.schedule.model;

public class ScheduleEventRepeat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_trade_event_repeat.repeat_key
     *
     * @mbggenerated Thu Aug 13 14:23:46 CST 2015
     */
    private String repeatKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_trade_event_repeat.repeat_key
     *
     * @return the value of cp_trade_event_repeat.repeat_key
     *
     * @mbggenerated Thu Aug 13 14:23:46 CST 2015
     */
    public String getRepeatKey() {
        return repeatKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_trade_event_repeat.repeat_key
     *
     * @param repeatKey the value for cp_trade_event_repeat.repeat_key
     *
     * @mbggenerated Thu Aug 13 14:23:46 CST 2015
     */
    public void setRepeatKey(String repeatKey) {
        this.repeatKey = repeatKey;
    }
}