package com.deppon.schedule.model;

import com.alibaba.fastjson.JSON;
import com.deppon.schedule.constant.ScheduleBizStatusConst;
import org.apache.commons.lang.StringUtils;

import java.io.IOException;
import java.io.Serializable;
import java.util.Date;

public class ScheduleItem<T> implements Serializable {

    private static final long serialVersionUID = -3802987624000294819L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.id
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.task_type
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private String taskType;// 任务类型
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.biz_id
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private String bizId;// 放订阅者
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.param
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private String param;// 消息

    private T paramObject;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.retry_nums
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private Integer retryNums;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.next_retry_time
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private Long nextRetryTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.biz_status
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private Integer bizStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.error_log
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private String errorLog;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.own_sign
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private String ownSign; // 隔离环境域

    /**
     * 应用名
     */
    private String application;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.remark
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.status
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.cdate
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private Date createDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mono_schedule_item.edate
     *
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    private Date modifyDate;

    /**
     * 判断今日星期几
     */
    private Integer dayWeek;

    /**
     * 判断当前时间上午下午
     */
    private Integer ampm;

    /**
     * 数据表number
     */
    private Integer tableNum;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.id
     *
     * @return the value of mono_schedule_item.id
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.id
     *
     * @param id the value for mono_schedule_item.id
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.task_type
     *
     * @return the value of mono_schedule_item.task_type
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.task_type
     *
     * @param taskType the value for mono_schedule_item.task_type
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.biz_id
     *
     * @return the value of mono_schedule_item.biz_id
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.biz_id
     *
     * @param bizId the value for mono_schedule_item.biz_id
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    /**
     * 获取对象
     */
    public T getParamObject(T t) throws IOException, ClassNotFoundException {

        // Json反序列化param
        paramObject = (T) JSON.parseObject(param, t.getClass());
        return paramObject;
    }

    /**
     * 设置对象
     */
    public void setParamObject(T paramObject) {
        this.paramObject = paramObject;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.param
     *
     * @return the value of mono_schedule_item.param
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public String getParam() {
        if (StringUtils.isNotBlank(param)) {
            return param;
        }
        // Json序列化paramObject
        param = JSON.toJSONString(paramObject);
        return param;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.param
     *
     * @param param the value for mono_schedule_item.param
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setParam(String param) {
        this.param = param;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.retry_nums
     *
     * @return the value of mono_schedule_item.retry_nums
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public Integer getRetryNums() {
        return retryNums;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.retry_nums
     *
     * @param retryNums the value for mono_schedule_item.retry_nums
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setRetryNums(Integer retryNums) {
        this.retryNums = retryNums;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.next_retry_time
     *
     * @return the value of mono_schedule_item.next_retry_time
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public Long getNextRetryTime() {
        return nextRetryTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.next_retry_time
     *
     * @param nextRetryTime the value for mono_schedule_item.next_retry_time
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setNextRetryTime(Long nextRetryTime) {
        this.nextRetryTime = nextRetryTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.biz_status
     *
     * @return the value of mono_schedule_item.biz_status
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public Integer getBizStatus() {
        return bizStatus;
    }

    public String getBizStatusName() {
        if (null != bizStatus) {
            if (ScheduleBizStatusConst.DEFAULT.value() == bizStatus) {
                return ScheduleBizStatusConst.DEFAULT.getCname();
            } else if (ScheduleBizStatusConst.SUCCESS.value() == bizStatus) {
                return ScheduleBizStatusConst.SUCCESS.getCname();
            } else if (ScheduleBizStatusConst.RETRY.value() == bizStatus) {
                return ScheduleBizStatusConst.RETRY.getCname();
            } else if (ScheduleBizStatusConst.ERROR.value() == bizStatus) {
                return ScheduleBizStatusConst.ERROR.getCname();
            }
        }
        return "未定义";
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.biz_status
     *
     * @param bizStatus the value for mono_schedule_item.biz_status
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setBizStatus(Integer bizStatus) {
        this.bizStatus = bizStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.error_log
     *
     * @return the value of mono_schedule_item.error_log
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public String getErrorLog() {
        return errorLog;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.error_log
     *
     * @param errorLog the value for mono_schedule_item.error_log
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setErrorLog(String errorLog) {
        this.errorLog = errorLog;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.own_sign
     *
     * @return the value of mono_schedule_item.own_sign
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public String getOwnSign() {
        return ownSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.own_sign
     *
     * @param ownSign the value for mono_schedule_item.own_sign
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setOwnSign(String ownSign) {
        this.ownSign = ownSign;
    }

    public String getApplication() {
        return application;
    }

    public void setApplication(String application) {
        this.application = application;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.remark
     *
     * @return the value of mono_schedule_item.remark
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.remark
     *
     * @param remark the value for mono_schedule_item.remark
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.status
     *
     * @return the value of mono_schedule_item.status
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.status
     *
     * @param status the value for mono_schedule_item.status
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.cdate
     *
     * @return the value of mono_schedule_item.cdate
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.cdate
     *
     * @param createDate the value for mono_schedule_item.cdate
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mono_schedule_item.edate
     *
     * @return the value of mono_schedule_item.edate
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mono_schedule_item.edate
     *
     * @param modifyDate the value for mono_schedule_item.edate
     * @mbggenerated Tue Aug 11 22:15:32 CST 2015
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }


    public Integer getDayWeek() {
        return dayWeek;
    }

    public void setDayWeek(Integer dayWeek) {
        this.dayWeek = dayWeek;
    }

    public Integer getAmpm() {
        return ampm;
    }

    public void setAmpm(Integer ampm) {
        this.ampm = ampm;
    }

    public Integer getTableNum() {
        return tableNum;
    }

    public void setTableNum(Integer tableNum) {
        this.tableNum = tableNum;
    }
}